name: WF RELEASE
on:
  push:
    branches: 
      - 'releases/*'
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches: 
      - 'releases/*'
  create:
    branches: 
      - releases/*   
jobs:
  job1:
    if: ${{ contains(github.ref, 'refs/heads/releases/') }}
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Correr pruebas
      id: correr-pruebas
      run: python src/codigo.py
  automerge:
    if: ${{ contains(github.event.head_commit.message, 'MERGE') }}
    name: merge-branch
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de repositorio
        uses: actions/checkout@v2

      - name: Merge release -> master
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: master
          github_token: ${{ github.token }}